### ISSUE TITLE
 "Unable to find a suitable output format"

### ISSUE THREAD

**Issue by NicklasOestergaard** [F0903/dr-downloader-cli#1]
I get the error "Unable to find a suitable output format". Does the program still work and can you show an example of how out sets up and send the commands?

**Comment by F0903** [comment]
Hey. It might be that DR has changed some stuff. I'll take a look at it when I have the time tomorrow

**Comment by F0903** [comment]
I'll also update the readme as it seems to be a bit lacking

**Comment by F0903** [comment]
I've pushed some new commits to the library. It's now working for me with every show I have tested, can you see if it's working for you now?

**Comment by NicklasOestergaard** [comment]
My anti-virus is blocking the file.  Even when I allow the file, it removes the file.

**Comment by F0903** [comment]
Could you try to temporarily disable the anti-virus for testing then?

**Comment by NicklasOestergaard** [comment]
Version 2.1.1 does not cause the same problems and works flawlessly. Thanks a lot.

**Comment by F0903** [comment]
That's good to hear. I'll close this issue then :)
