### ISSUE TITLE
Invalid passthrough (internal error)

### ISSUE THREAD

**Issue by itzcali** [F0903/dr-downloader-cli#2]
I'm trying to download a video using this command:

`dr-downloader-cli.exe download https://www.dr.dk/drtv/se/techfix_-bliver-til-en-tatovering_406721`

This gives the error:

`←[91mError!←[0m Invalid passthrough (internal error)`

I trust the token is valid and I have included it here for reference. Any idea why the error is occurring?

`dr-downloader-cli.exe token get
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJzaWQiOiIxZDRkNDc5Ni05NjQ2LTQyNmUtODQ2My1mNDVhMzZiZDc2NmIiLCJzcHIiOiJOb25lIiwiYXVkIjoiaHR0cDovL2lzbC5kci1tYXNzaXZlLmNvbS9JU0wvQXBpL1YxL0RhdGFzZXJ2aWNlIiwic3ViIjoiQ2F0YWxvZyIsImV4cCI6MTY5ODIyMDQxMCwidXNlckFjY291bnRJZCI6IjExNTBhNWE5ODc5YTRhMTliMDZkYjk1Mjc2MmI0YjhhIiwidXNlclByb2ZpbGVJZCI6IjExNTBhNWE5ODc5YTRhMTliMDZkYjk1Mjc2MmI0YjhhIiwiZW1haWwiOiIxMTUwYTVhOTg3OWE0YTE5YjA2ZGI5NTI3NjJiNGI4YUBleGFtcGxlLmNvbSIsImRldmljZSI6IndlYl9icm93c2VyIiwidmFsaWRVbnRpbCI6MTcwMDc2OTIxMCwiaWF0IjoxNjk4MTc3MjEwLCJpc09wdGVkT3V0Ijp0cnVlLCJpc0NvdW50cnlWZXJpZmllZCI6ZmFsc2UsImdlb0xvY2F0aW9uIjoiZGsiLCJpc0RldmljZUFicm9hZCI6ZmFsc2UsImlzRmFsbGJhY2tUb2tlbiI6ZmFsc2UsImNvbnNlbnQiOltdfQ.zgTSMy309vX10KnTcJywLfGduYYOvMczmKEFUnJNZYrtqIAsQXTaV5cB7JFA9kHAGVBirkv3-fn1jpMFZPjWv2MWoLabeLWu6IK7NYEdQiHMWuA__KD1IFBNO2ef0dWR-_Ux07zXLjb1msgQa_xm3HqecGKb_w6oZq09Mi6jNXBZ-Fd9onC2xS8zJWV5VeARY03TZpoT3QGhQbcPA42kj7JP1fEXp_d4Wzyj0bgv6O0O8JT7NZK9VbjiKegLd7iQ23QjpNF8swdWSrlGpFx2I_TL71UNjJn_DR9HMVzuaaw1NOTgyI7WG0WEWwKnRtLrEOmWmMF4DCa3rolGpxh4ug`

**Comment by F0903** [comment]
Very strange. I'll take a look at it this weekend.

**Comment by F0903** [comment]
I got to it now instead, it should be fixed. It's at least working for me now :)

When the release workflow is done in a minute or two from now, you should be able to download the new 2.1.4 release (or build the new source yourself :)). Could you then confirm then that it works for you as well?

**Comment by itzcali** [comment]
Verified - works like a charm - thank you much @F0903 :)
